DELIMITER $$

USE `KMMI5`$$

DROP FUNCTION IF EXISTS `GenidTB`$$

CREATE DEFINER=`student`@`%` FUNCTION `GenidTB`() RETURNS VARCHAR(11) CHARSET utf8mb4
    READS SQL DATA
BEGIN
DECLARE idtb VARCHAR(11);

SELECT CONCAT(DATE_FORMAT(NOW(),'%Y%m%d'),
LPAD(IFNULL(SUBSTR(MAX(id_tb),9,3),0)+1,3,'0')) INTO idtb
FROM transaksi_beli WHERE SUBSTR(id_tb,1,8) = DATE_FORMAT(NOW(),'%Y%m%d');

RETURN idtb;
END$$

DELIMITER ;